# Print Simple Welcoming Message
print(
    "Welcome to this computer Quiz game! which has generated by Python Programming Language".title()
)

# Get the Player Opinion About Gaming or not
playing = input("do you want to play?! ").title()

# If User Do Not Want To Play => End!!!
if playing.lower() != "yes":
    quit()
print("Excellent! Let's Go 😁")

# implement a Score
score = 0

# Main Question of the Game <Start The Game>
userAnswer = input("1- What Does CPU stands for? ")
if userAnswer.lower() == "central processing unit":
    print("Great, It Is Correct!")
    score += 1
    print("Your Score Is:", score)
else:
    print("Incorrect!!!")
    score -= 1
    print("Your Score Is:", score)

# Question 2
userAnswer = input("2-What Does GPU stands for? ")
if userAnswer.lower() == "graphics processing unit":
    print("Great, It Is Correct!")
    score += 1
    print("Your Score Is:", score)
else:
    print("Incorrect!!!")
    score -= 1
    print("Your Score Is:", score)

# Question 3
userAnswer = input("3-What Does RAM stands for? ")
if userAnswer.lower() == "random access memory":
    print("Great, It Is Correct!")
    score += 1
    print("Your Score Is:", score)
else:
    print("Incorrect!!!")
    score -= 1
    print("Your Score Is:", score)

# Question 4
userAnswer = input("4-What Does PSU stands for? ")
if userAnswer.lower() == "power supplier unit":
    print("Great, It Is Correct!")
    score += 1
    print("Your Score Is:", score)
else:
    print("Incorrect!!!")
    score -= 1
    print("Your Score Is:", score)

# Print The Final Score
print(f"You Got {score} From 5 Of Correct Questions😊")

# representing Score In percentage
print(f"You Got {(score / 4) * 100}% From Total 100% Of Correct Questions😊")
